### ISSUE TITLE
目前最新版本不能看到最后一行

### ISSUE THREAD

**Issue by guzeh** [syfxlin/xkeditor#15]
目前最新版本不能看到最后一行

**Comment by syfxlin** [comment]
@guzeh 最新的push已经修复了，不过1.4.8版本应该是没有这个问题的（master分支在 [7d4178e](https://github.com/syfxlin/xkeditor/commit/7d4178e41038d9edc8a672355fd46a10cecf72a3) 之后的是1.4.9-pre）
