### ISSUE TITLE
功能上的一些建议

### ISSUE THREAD

**Issue by learn2s** [syfxlin/xkeditor#16]
繁星大大，试用演示感觉挺赞的，看到里面有画图的模块，有没有想过类似嵌入 drawio 的画图？类似于 bookstackapp 。

另外「引用」的多样式表现类似于 Origami Notebox 区块能在 xkeditor 实现吗？

**Comment by syfxlin** [comment]
@learn2s Notebox在最新版已经实现，drawio的画图不会在xkeditor中实现，不过有打算给xknote弄一个。
